# WINDOWS SIZE
# MainWindow size
MAIN_WINDOW_WIDTH = 800
MAIN_WINDOW_HEIGHT = 500

# Home size
HOME_WIDTH = 600
HOME_HEIGHT = 400

# DVR size
DVR_WIDTH = 1000
DVR_HEIGHT = 600

# BUTTONS SIZE
# Load button size
LOAD_BUTTON_WIDTH = 250
LOAD_BUTTON_HEIGHT = 50

# Menu buttons size
MENU_BUTTON_WIDTH = 30
MENU_BUTTON_HEIGHT = 30

# Standard button size
STANDARD_BUTTON_WIDTH = 90
STANDARD_BUTTON_HEIGHT = 20

# Search bar size
SEARCH_BAR_WIDTH = 400
SEARCH_BAR_HEIGHT = 30

# LABELS SIZE
# Load label size
LOAD_LABEL_SEZE = 20

# FILE AUDIO IMG SIZE
FILE_AUDIO_IMG_WIDTH = 30
FILE_AUDIO_IMG_HEIGHT = 30

# PLAYER PATH
PLAYER_PATH = r"mnt/c/Program Files/VideoLAN/VLC/vlc.exe"