class Constants:
     # PLAYER PATH
    PLAYER_PATH = r"mnt/c/Program Files/VideoLAN/VLC/vlc.exe"
    # WINDOWS SIZE
    MAIN_WINDOW_WIDTH = 800
    MAIN_WINDOW_HEIGHT = 500
    HOME_VIEW_WIDTH = 600
    HOME_VIEW_HEIGHT = 400
    DVR_VIEW_WIDTH = 1000
    DVR_VIEW_HEIGHT = 600
    # BUTTONS SIZE
    LOAD_BUTTON_WIDTH = 250
    LOAD_BUTTON_HEIGHT = 50
    MENU_BUTTON_WIDTH = 30
    MENU_BUTTON_HEIGHT = 30
    STANDARD_BUTTON_WIDTH = 90
    STANDARD_BUTTON_HEIGHT = 20
    # Search bar size
    SEARCH_BAR_WIDTH = 400
    SEARCH_BAR_HEIGHT = 30
    # LABELS SIZE
    LOAD_LABEL_SIZE = 20
    # FILE AUDIO IMG SIZE
    FILE_AUDIO_IMG_WIDTH = 30
    FILE_AUDIO_IMG_HEIGHT = 30
